### ISSUE TITLE
Documentation generation

### ISSUE THREAD

**Issue by chris-armstrong** [chris-armstrong/smaws#8]
Generate API Reference Documentation from the embedded documentation in the Smithy definitions

**Comment by vouillon** [comment]
I had started a similar project: https://github.com/vouillon/ocaml-smithy.
I did not go as far as this project, but I was generating some documentation from the Smithy definitions. Maybe you can reuse some of the code?
![image](https://github.com/user-attachments/assets/f3e023d1-f36e-427d-9351-a2f75f70c617)
![image](https://github.com/user-attachments/assets/b3935a43-b14d-4a78-82a2-1cde393ef62a)

**Comment by chris-armstrong** [comment]
Thanks for sharing that.

I'm have something relatively close to ready  documentation wise in #14, I might just pull over some of your markup parser rules.

 There's a lot in your code I could use regarding code generation and documentation parsing. I need to clean up my code generator anyway; switching to ppxlib doesn't seem like a bad idea, but I wonder if it's just faster to output text.

**Comment by vouillon** [comment]
> There's a lot in your code I could use regarding code generation and documentation parsing. I need to clean up my code generator anyway; switching to ppxlib doesn't seem like a bad idea, but I wonder if it's just faster to output text.

Using ppxlib has the advantage that you are sure to generate syntactically correct code. But it's indeed harder to use.
